...

diff --git a/.x-cmd/fabu-yy b/.x-cmd/fabu-yy
--- a/.x-cmd/fabu-yy
+++ b/.x-cmd/fabu-yy
@@ -47,7 +47,11 @@ function update_mod(){
     yy:info "gitb路径 $gibpath"
     if [ -d "mod/$mod" ]; then
         yy:info "update - git subtree pull"
-        git subtree pull  --prefix="mod/$mod" "$gibpath" main  --squash
+        git subtree pull  --prefix="mod/$mod" "$gibpath" main  --squash || {
+            yy:warn "Update Failed, will be deleted and re-cloned."
+            __x_cmd rmrf "mod/$mod"
+            git subtree add   --prefix="mod/$mod" --squash "$gibpath" main
+        }
     else
         yy:info "add - git subtree add"
         git subtree add   --prefix="mod/$mod" --squash "$gibpath" main
